FROM maven:3.9.6-amazoncorretto-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17
COPY backend/target/*.jar /app.jar
CMD ["java", "-jar", "/app.jar"]

FROM amazoncorretto:21
WORKDIR /app
COPY --from=builder /app/target/MusicCatalog-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "MusicCatalog-0.0.1-SNAPSHOT.jar"]